- hosts: "{{ srv }}"
  become: true
  roles:
    #- { role: docker, tags: ["docker"]} 
    #- { role: elasticsearch, tags: ["elasticsearch"]}
    - { role: logstash, tags: ["logstash"]}
    #- { role: kibana, tags: ["kibana"]}